# Generated by Django 3.0.3 on 2020-02-27 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='creatd',
            new_name='created',
        ),
    ]
